### ISSUE TITLE
Kill React Native packager

### ISSUE THREAD

**Issue by Minishlink** [taboulot/rn-game-over#1]

**Comment by gh-clement-taboulot** [comment]
@Minishlink

Any idea about how to do that ?

**Comment by markrickert** [comment]
you should be able to do that with: `pkill -f 'cli.js start'`. I have that in my `package.json` postinstall script.

**Comment by lucassus** [comment]
I use something like:

```
# Kill the package manager on port 8081
lsof -n -i4TCP:8081 | sed '1 d' | awk '{print $2}' | xargs kill -9
```

**Comment by gh-clement-taboulot** [comment]
@markrickert & @lucassus thanks for answers !

@lucassus feel free to create a PR for your implementation if you want :)
